//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Chapter2Interfaces
{
    [Serializable]
    public class CalculateCylinderVolumeResponse : Message
    {
        public const string k_RosMessageName = "chapter2_interfaces/CalculateCylinderVolume";
        public override string RosMessageName => k_RosMessageName;

        public double v;

        public CalculateCylinderVolumeResponse()
        {
            this.v = 0.0;
        }

        public CalculateCylinderVolumeResponse(double v)
        {
            this.v = v;
        }

        public static CalculateCylinderVolumeResponse Deserialize(MessageDeserializer deserializer) => new CalculateCylinderVolumeResponse(deserializer);

        private CalculateCylinderVolumeResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.v);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.v);
        }

        public override string ToString()
        {
            return "CalculateCylinderVolumeResponse: " +
            "\nv: " + v.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
