//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Chapter2Interfaces
{
    [Serializable]
    public class CalculateCylinderVolumeRequest : Message
    {
        public const string k_RosMessageName = "chapter2_interfaces/CalculateCylinderVolume";
        public override string RosMessageName => k_RosMessageName;

        public double r;
        public double h;

        public CalculateCylinderVolumeRequest()
        {
            this.r = 0.0;
            this.h = 0.0;
        }

        public CalculateCylinderVolumeRequest(double r, double h)
        {
            this.r = r;
            this.h = h;
        }

        public static CalculateCylinderVolumeRequest Deserialize(MessageDeserializer deserializer) => new CalculateCylinderVolumeRequest(deserializer);

        private CalculateCylinderVolumeRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.r);
            deserializer.Read(out this.h);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.r);
            serializer.Write(this.h);
        }

        public override string ToString()
        {
            return "CalculateCylinderVolumeRequest: " +
            "\nr: " + r.ToString() +
            "\nh: " + h.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
