//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Chapter4Interfaces
{
    [Serializable]
    public class ServoPositionServiceResponse : Message
    {
        public const string k_RosMessageName = "chapter4_interfaces/ServoPositionService";
        public override string RosMessageName => k_RosMessageName;

        public string result;

        public ServoPositionServiceResponse()
        {
            this.result = "";
        }

        public ServoPositionServiceResponse(string result)
        {
            this.result = result;
        }

        public static ServoPositionServiceResponse Deserialize(MessageDeserializer deserializer) => new ServoPositionServiceResponse(deserializer);

        private ServoPositionServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "ServoPositionServiceResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
